name: pytorch-transformer
channels:
  - defaults
  - pytorch
dependencies:
  - python==3.8.3
  - pip==20.0.2
  - matplotlib==3.1.3
  - pytorch==1.5.0
  - torchtext==0.6.0
  - pip:
    - GitPython==3.1.2
    - jupyter==1.0.0
    - numpy==1.18.4
    - tensorboard==2.2.2
    - nltk==3.5
    - seaborn==0.11.0
    - spacy==2.3.2
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz#egg=en_core_web_sm
    - https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.3.0/de_core_news_sm-2.3.0.tar.gz#egg=de_core_news_sm